name: bert24
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.12
  - antlr-python-runtime=4.9.3
  - anyio=4.4.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argcomplete=3.5.0
  - arrow=1.3.0
  - attrs=24.2.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.5
  - aws-sdk-cpp=1.11.379
  - azure-core=1.30.2
  - azure-core-cpp=1.13.0
  - azure-identity=1.17.1
  - azure-identity-cpp=1.8.0
  - azure-storage-blob=12.22.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-file-datalake=12.16.0
  - azure-storage-files-datalake-cpp=12.11.0
  - backoff=2.2.1
  - bcrypt=4.2.0
  - binaryornot=0.4.4
  - binutils=2.40
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.0
  - boto3=1.35.2
  - botocore=1.35.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - c-compiler=1.7.0
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - cairo=1.18.0
  - cccl=2.3.1
  - certifi=2024.7.4
  - cffi=1.17.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - circuitbreaker=1.4.0
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.1
  - cookiecutter=2.6.0
  - coolname=2.2.0
  - cramjam=2.8.3
  - cryptography=41.0.7
  - cuda=12.4.0
  - cuda-cccl=12.4.99
  - cuda-cccl_linux-64=12.4.99
  - cuda-command-line-tools=12.4.0
  - cuda-compiler=12.4.0
  - cuda-crt-dev_linux-64=12.4.99
  - cuda-crt-tools=12.4.99
  - cuda-cudart=12.4.99
  - cuda-cudart-dev=12.4.99
  - cuda-cudart-dev_linux-64=12.4.99
  - cuda-cudart-static=12.4.99
  - cuda-cudart-static_linux-64=12.4.99
  - cuda-cudart_linux-64=12.4.99
  - cuda-cuobjdump=12.4.99
  - cuda-cupti=12.4.99
  - cuda-cupti-dev=12.4.99
  - cuda-cuxxfilt=12.4.99
  - cuda-demo-suite=12.4.127
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.4.99
  - cuda-driver-dev_linux-64=12.4.127
  - cuda-gdb=12.4.99
  - cuda-libraries=12.4.0
  - cuda-libraries-dev=12.4.0
  - cuda-libraries-static=12.6.0
  - cuda-nsight=12.4.99
  - cuda-nsight-compute=12.4.0
  - cuda-nvcc=12.4.99
  - cuda-nvcc-dev_linux-64=12.4.99
  - cuda-nvcc-impl=12.4.99
  - cuda-nvcc-tools=12.4.99
  - cuda-nvcc_linux-64=12.4.99
  - cuda-nvdisasm=12.4.99
  - cuda-nvml-dev=12.4.99
  - cuda-nvprof=12.4.99
  - cuda-nvprune=12.4.99
  - cuda-nvrtc=12.4.99
  - cuda-nvrtc-dev=12.4.99
  - cuda-nvrtc-static=12.4.99
  - cuda-nvtx=12.4.99
  - cuda-nvvm-dev_linux-64=12.4.99
  - cuda-nvvm-impl=12.4.99
  - cuda-nvvm-tools=12.4.99
  - cuda-nvvp=12.4.99
  - cuda-opencl=12.4.99
  - cuda-opencl-dev=12.4.99
  - cuda-profiler-api=12.4.99
  - cuda-runtime=12.4.0
  - cuda-sanitizer-api=12.4.99
  - cuda-toolkit=12.4.0
  - cuda-tools=12.4.0
  - cuda-version=12.4
  - cuda-visual-tools=12.4.0
  - cxx-compiler=1.7.0
  - cycler=0.12.1
  - dataclasses=0.8
  - datasets=2.21.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - double-conversion=3.3.0
  - einops=0.8.0
  - evaluate=0.4.1
  - exceptiongroup=1.2.2
  - execnet=2.1.1
  - expat=2.6.2
  - ffmpeg=7.0.1
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gcc_linux-64=12.4.0
  - gds-tools=1.9.0.20
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - google-api-core=2.19.1
  - google-auth=2.33.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.10.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.63.2
  - gql=3.5.0
  - graphite2=1.3.13
  - graphql-core=3.2.3
  - grpcio=1.62.2
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - gxx_linux-64=12.4.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hpack=4.0.0
  - huggingface_hub=0.24.6
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.4.0
  - iniconfig=2.0.0
  - intel-openmp=2022.0.1
  - isodate=0.6.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcublas=12.4.2.65
  - libcublas-dev=12.4.2.65
  - libcublas-static=12.4.2.65
  - libcufft=11.2.0.44
  - libcufft-dev=11.2.0.44
  - libcufft-static=11.2.0.44
  - libcufile=1.9.0.20
  - libcufile-dev=1.9.0.20
  - libcufile-static=1.9.0.20
  - libcups=2.3.3
  - libcurand=10.3.5.119
  - libcurand-dev=10.3.5.119
  - libcurand-static=10.3.5.119
  - libcurl=8.9.1
  - libcusolver=11.6.0.99
  - libcusolver-dev=11.6.0.99
  - libcusolver-static=11.6.0.99
  - libcusparse=12.3.0.142
  - libcusparse-dev=12.3.0.142
  - libcusparse-static=12.3.0.142
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgirepository=1.80.1
  - libglib=2.80.2
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm18=18.1.8
  - libnghttp2=1.58.0
  - libnpp=12.2.5.2
  - libnpp-dev=12.2.5.2
  - libnpp-static=12.2.5.2
  - libnsl=2.0.1
  - libnuma=2.0.18
  - libnvfatbin=12.4.99
  - libnvfatbin-dev=12.4.99
  - libnvfatbin-static=12.4.127
  - libnvjitlink=12.4.99
  - libnvjitlink-dev=12.4.99
  - libnvjitlink-static=12.4.127
  - libnvjpeg=12.3.1.89
  - libnvjpeg-dev=12.3.1.89
  - libnvjpeg-static=12.3.1.89
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-intel-npu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=12.4.0
  - libsecret=0.18.8
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.21.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxkbfile=1.1.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning-utilities=0.11.6
  - llvm-openmp=15.0.7
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mdurl=0.1.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msal=1.30.0
  - msal_extensions=1.1.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - nsight-compute=2024.1.0.13
  - nspr=4.35
  - nss=3.103
  - numba=0.60.0
  - numpy=1.26.4
  - oci=2.132.0
  - ocl-icd=2.3.2
  - omegaconf=2.3.0
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.2
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - paramiko=3.4.1
  - pathtools=0.1.2
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - portalocker=2.10.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pugixml=1.14
  - py-cpuinfo=9.0.0
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycairo=1.26.1
  - pycparser=2.22
  - pygments=2.18.0
  - pygobject=3.48.2
  - pyjwt=2.9.0
  - pynacl=1.5.0
  - pyopenssl=23.3.0
  - pyparsing=3.1.2
  - pyside6=6.7.2
  - pysocks=1.7.1
  - pytest=8.3.2
  - pytest-xdist=3.6.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-slugify=8.0.4
  - python-snappy=0.7.2
  - python-tzdata=2024.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytorch-ranger=0.1.1
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.7.2
  - questionary=2.0.1
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - responses=0.18.0
  - rich=13.7.1
  - rsa=4.9
  - s2n=1.5.1
  - s3transfer=0.10.2
  - safetensors=0.4.4
  - sentry-sdk=2.13.0
  - setproctitle=1.3.3
  - setuptools=72.2.0
  - shellingham=1.5.4
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - svt-av1=2.1.0
  - sympy=1.13.2
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.12.0
  - termcolor=2.4.0
  - text-unidecode=1.3
  - tk=8.6.13
  - tokenizers=0.19.1
  - tomli=2.0.1
  - torch-optimizer=0.3.0
  - torchaudio=2.4.0
  - torchmetrics=1.4.0.post0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - transformers=4.44.1
  - typer=0.12.4
  - typer-slim=0.12.4
  - typer-slim-standard=0.12.4
  - types-python-dateutil=2.9.0.20240821
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - validators=0.33.0
  - wandb=0.16.6
  - wayland=1.23.0
  - wcwidth=0.2.13
  - websockets=11.0.3
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.20.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - pip:
      - mosaicml==0.24.1
      - mosaicml-cli==0.6.41
      - mosaicml-streaming==0.8.0
      - ninja==1.11.1.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - torch-optimi==0.2.1
      - zstd==1.5.5.1
